### ISSUE TITLE
Maximum number of extracted entries

### ISSUE THREAD

**Issue by PScharner** [Patent2net/P2N-v3#2]
To whom it may concern, 

I was trying to extract a larger amount of patents using P2N-v3 which appears to be a great package! Thank you very much for coding it by the way! 
However, there seems to be a maximum number of 2,000 entries that can be extracted. How can I increase this number manually? Where do I find the particular file?

I am really looking forward to your response.

Best regards,
Philipp

**Comment by Quoniam** [comment]
https://github.com/Patent2net/P2N-v3/issues/1#issuecomment-510884969
